-- Departments table setup for College ERP
-- Departments belong to Schools/Faculties

-- Create departments table
CREATE TABLE IF NOT EXISTS public.departments (
  id bigint generated by default as identity not null,
  school_id bigint not null,
  name character varying(150) not null,
  code character varying(20) null,
  description text null,
  hod_name character varying(120) null,
  contact_email character varying(120) null,
  is_active boolean null default true,
  created_at timestamp with time zone null default now(),
  constraint departments_pkey primary key (id),
  constraint departments_code_key unique (code),
  constraint departments_school_id_fkey foreign key (school_id) references public.schools(id) on delete restrict
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_departments_school_id ON public.departments(school_id);
CREATE INDEX IF NOT EXISTS idx_departments_code ON public.departments(code);
CREATE INDEX IF NOT EXISTS idx_departments_is_active ON public.departments(is_active);
CREATE INDEX IF NOT EXISTS idx_departments_name ON public.departments(name);

-- Verify table and relationships
-- Run this query to see departments with their schools:
-- SELECT d.id, d.name, d.code, s.name as school_name, d.hod_name, d.is_active 
-- FROM public.departments d
-- LEFT JOIN public.schools s ON d.school_id = s.id
-- ORDER BY s.name, d.name;

-- Optional: Insert sample data (requires schools to exist first)
-- Uncomment and modify school_id values based on your actual schools:
/*
INSERT INTO public.departments (school_id, name, code, description, hod_name, contact_email, is_active)
VALUES 
  (1, 'Computer Science', 'CS', 'Department of Computer Science', 'Dr. Alice Johnson', 'alice.j@college.edu', true),
  (1, 'Electrical Engineering', 'EE', 'Department of Electrical Engineering', 'Dr. Bob Smith', 'bob.s@college.edu', true),
  (2, 'Physics', 'PHY', 'Department of Physics', 'Dr. Carol White', 'carol.w@college.edu', true)
ON CONFLICT (code) DO NOTHING;
*/
