-- Schools table setup for College ERP
-- ✅ TABLE ALREADY EXISTS IN YOUR SUPABASE DATABASE

-- Existing table structure:
CREATE TABLE public.schools (
  id bigint generated by default as identity not null,
  name character varying(150) not null,
  code character varying(20) null,
  description text null,
  dean_name character varying(120) null,
  contact_email character varying(120) null,
  contact_phone character varying(20) null,
  is_active boolean null default true,
  created_at timestamp with time zone null default now(),
  constraint schools_pkey primary key (id),
  constraint schools_code_key unique (code)
);

-- Optional: Add helpful indexes for better performance
CREATE INDEX IF NOT EXISTS idx_schools_code ON public.schools(code);
CREATE INDEX IF NOT EXISTS idx_schools_is_active ON public.schools(is_active);
CREATE INDEX IF NOT EXISTS idx_schools_name ON public.schools(name);

-- Verify table exists and check current data
-- Run this query in Supabase SQL Editor to see your schools:
SELECT id, name, code, dean_name, contact_email, is_active, created_at 
FROM public.schools 
ORDER BY name;

-- Optional: Insert sample data if your table is empty
-- Uncomment and run if you need test data:
/*
INSERT INTO public.schools (name, code, description, dean_name, contact_email, contact_phone, is_active)
VALUES 
  ('School of Engineering', 'ENG', 'Faculty of Engineering and Technology', 'Dr. John Smith', 'john.smith@college.edu', '+1-555-0101', true),
  ('School of Sciences', 'SCI', 'Faculty of Natural and Applied Sciences', 'Dr. Sarah Johnson', 'sarah.johnson@college.edu', '+1-555-0102', true),
  ('School of Arts', 'ARTS', 'Faculty of Arts and Humanities', 'Dr. Michael Brown', 'michael.brown@college.edu', '+1-555-0103', true)
ON CONFLICT (code) DO NOTHING;
